/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto1;

/**
 *
 * @author USER
 */
public class Ventana extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana.class.getName());

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup_sexo = new javax.swing.ButtonGroup();
        jLavelNombre = new javax.swing.JLabel();
        jTextField_Nombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        jTextField_Apellido = new javax.swing.JTextField();
        jLabel_Sexo = new javax.swing.JLabel();
        jRadioButton_sexo_Hombre = new javax.swing.JRadioButton();
        jRadioButton_sexo_Mujer = new javax.swing.JRadioButton();
        jRadioButton_sexo_Nunca = new javax.swing.JRadioButton();
        jLabel_NumeroTarjeta = new javax.swing.JLabel();
        jLabel_Caducidad = new javax.swing.JLabel();
        jLabel_CodigoSeguridad = new javax.swing.JLabel();
        jTextField_NumTarjeta = new javax.swing.JTextField();
        jTextField_Caducidad = new javax.swing.JTextField();
        jTextField_CodigoSeguridad = new javax.swing.JTextField();
        Baceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLavelNombre.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLavelNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(76, 62, 0, 0);
        getContentPane().add(jLavelNombre, gridBagConstraints);

        jTextField_Nombre.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 183;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(76, 6, 0, 0);
        getContentPane().add(jTextField_Nombre, gridBagConstraints);

        jLabelApellido.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabelApellido.setText("Apellido:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 62, 0, 0);
        getContentPane().add(jLabelApellido, gridBagConstraints);

        jTextField_Apellido.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 183;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        getContentPane().add(jTextField_Apellido, gridBagConstraints);

        jLabel_Sexo.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel_Sexo.setText("Sexo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 80, 0, 0);
        getContentPane().add(jLabel_Sexo, gridBagConstraints);

        buttonGroup_sexo.add(jRadioButton_sexo_Hombre);
        jRadioButton_sexo_Hombre.setText("Hombre");
        jRadioButton_sexo_Hombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_sexo_HombreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 80, 0, 0);
        getContentPane().add(jRadioButton_sexo_Hombre, gridBagConstraints);

        buttonGroup_sexo.add(jRadioButton_sexo_Mujer);
        jRadioButton_sexo_Mujer.setText("Mujer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 80, 0, 0);
        getContentPane().add(jRadioButton_sexo_Mujer, gridBagConstraints);

        buttonGroup_sexo.add(jRadioButton_sexo_Nunca);
        jRadioButton_sexo_Nunca.setText("Nunca");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 80, 0, 0);
        getContentPane().add(jRadioButton_sexo_Nunca, gridBagConstraints);

        jLabel_NumeroTarjeta.setText("Numero de Tarjeta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 107, 0, 0);
        getContentPane().add(jLabel_NumeroTarjeta, gridBagConstraints);

        jLabel_Caducidad.setText("Caducidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 107, 0, 0);
        getContentPane().add(jLabel_Caducidad, gridBagConstraints);

        jLabel_CodigoSeguridad.setText("CVC/CCV:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 9, 0, 0);
        getContentPane().add(jLabel_CodigoSeguridad, gridBagConstraints);

        jTextField_NumTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NumTarjetaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 118;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 107, 0, 77);
        getContentPane().add(jTextField_NumTarjeta, gridBagConstraints);

        jTextField_Caducidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CaducidadActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 107, 0, 0);
        getContentPane().add(jTextField_Caducidad, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 0, 77);
        getContentPane().add(jTextField_CodigoSeguridad, gridBagConstraints);

        Baceptar.setText("Aceptar");
        Baceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BaceptarMouseClicked(evt);
            }
        });
        Baceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaceptarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(61, 6, 21, 0);
        getContentPane().add(Baceptar, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_sexo_HombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_sexo_HombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_sexo_HombreActionPerformed

    private void jTextField_NumTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NumTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NumTarjetaActionPerformed

    private void jTextField_CaducidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CaducidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CaducidadActionPerformed

    private void BaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BaceptarActionPerformed

    private void BaceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BaceptarMouseClicked
        // TODO add your handling code here:
        String nombre, apellido, ntarjeta,fcaducidad, ccv, sexo;
        
        nombre = jTextField_Nombre.getText();
        apellido = jTextField_Apellido.getText();
        ntarjeta = jTextField_NumTarjeta.getText();
        fcaducidad = jTextField_Caducidad.getText();
        ccv = jTextField_CodigoSeguridad.getText();
        
        if (jRadioButton_sexo_Hombre.isSelected() == true){
            sexo = "Hombre";
        }
        else if (jRadioButton_sexo_Mujer.isSelected()){
            sexo = "Mujer";
        }
        else{
            sexo = "Nunca";
        }
        
        System.out.println("=================================================");
        System.out.println("Nombre: "+nombre+"\nApellido: "+apellido+"\nSexo: "+sexo+"\nNumero de tarjeta: "+ntarjeta+"\nFecha de caducidad:"+fcaducidad+"\nCodigo de seguridad: "+ccv);
        System.out.println("=================================================");
    }//GEN-LAST:event_BaceptarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ventana().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Baceptar;
    private javax.swing.ButtonGroup buttonGroup_sexo;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabel_Caducidad;
    private javax.swing.JLabel jLabel_CodigoSeguridad;
    private javax.swing.JLabel jLabel_NumeroTarjeta;
    private javax.swing.JLabel jLabel_Sexo;
    private javax.swing.JLabel jLavelNombre;
    private javax.swing.JRadioButton jRadioButton_sexo_Hombre;
    private javax.swing.JRadioButton jRadioButton_sexo_Mujer;
    private javax.swing.JRadioButton jRadioButton_sexo_Nunca;
    private javax.swing.JTextField jTextField_Apellido;
    private javax.swing.JTextField jTextField_Caducidad;
    private javax.swing.JTextField jTextField_CodigoSeguridad;
    private javax.swing.JTextField jTextField_Nombre;
    private javax.swing.JTextField jTextField_NumTarjeta;
    // End of variables declaration//GEN-END:variables
}
